/// LocalWave — Flutter generated file for splash screen.
/// Do not edit by hand.
///
/// This file is auto-generated by flutter_native_splash.
/// To regenerate, run: dart run flutter_native_splash:create
///
/// This class was generated by flutter_native_splash.
/// It may not be used.
// ignore_for_file: must_be_immutable

import 'package:flutter/material.dart';

class SplashScreen extends StatelessWidget {
  const SplashScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      backgroundColor: Color(0xFF121212),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(
              Icons.music_note_rounded,
              color: Color(0xFF1ED760),
              size: 80,
            ),
            SizedBox(height: 16),
            Text(
              'LocalWave',
              style: TextStyle(
                color: Colors.white,
                fontSize: 28,
                fontWeight: FontWeight.w700,
                letterSpacing: 0.5,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
